version: '2'
services: 
  nginx-proxy-oauth:
    image: tokyohomesoc/nginx-proxy-oauth
    container_name: nginx-proxy-oauth
    restart: always
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/rancher/nginx/certs:/etc/nginx/certs:ro
      - /home/rancher/nginx/conf.d:/etc/nginx/conf.d
      - /home/rancher/nginx/vhost.d:/etc/nginx/vhost.d
      - /home/rancher/nginx/html:/usr/share/nginx/html
  oauth2_proxy:
    image: tokyohomesoc/docker-oauth2_proxy
    container_name: oauth2_proxy
    restart: always
    links: 
      - nginx-proxy-oauth
    command: ["--email-domain="yourcompany.com"", "--upstream=http://127.0.0.1:8080/", "--cookie-secret=", "--provider=", "--client-id=", "--client-secret="]
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy-oauth
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /home/rancher/nginx/certs:/etc/nginx/certs:rw
    volumes_from:
    - nginx-proxy-oauth